### ISSUE TITLE
Crash with Chiselandbits

### ISSUE THREAD

**Issue by DatrixTHLK** [elix-x/Forever-Enough-Items#32]
Hello,
My game is crashing when I look up chiselandbits mod items in the item subset list.
Recent version of forge: 12.18.1.2035
Recent version of this mod: 1.0.15
Minecraft version: 1.10.2
http://pastebin.com/23yjhyG1

**Comment by Elix-x** [comment]
This is very weird FEI-JEI-C&B-Forestry interaction.
Poking @AlgorithmX2, @mezz.

**Comment by DatrixTHLK** [comment]
I guess neither one had an answer.

**Comment by Elix-x** [comment]
I guess. Also the crash is gone (second time pastebin does this to me in 24 hours), please reupload (if you still have it) so i can either fix it on my side or PR fix to responsible mod.

**Comment by mezz** [comment]
I remember looking at it earlier but had no idea what would have caused the issue.

**Comment by DatrixTHLK** [comment]
I will then need to re-download Chisel and bits mod. Will do so once this mod is updated to see if that might first fix said issue. Thanks for the response.

**Comment by Elix-x** [comment]
I released 1.0.16. Please confirm this is still a bug.

**Comment by DatrixTHLK** [comment]
I can confirm it is working now but there is this flickering game screen when looking at it. Most likely a graphical bug. I'm trying to determine at this point what mod would cause that issue with the game. I have a feeling it is chisel and bits.

**Edit 11:15pm**: Chisel & Bits gave me that weird graphical bug. Once it was taken out the graphical issue went away.

**Comment by DatrixTHLK** [comment]
Looks like AlgorithmX2 is still having the same issue as I did where having FEI and his mod installed just crashed the game when looking into subset menu. Seems like this mod and chisel and bits aren't cooperating.

**Comment by DatrixTHLK** [comment]
Latest issue with Chisel and bits 12.4 crashed me to desktop when looking into Item subset menu chisel and bits

Minecraft 1.10.2 
Forge: 2095
JEI 3.12.5.298
FEI 1.0.16
Chisel & Bits: 12.4

Crash Report: https://gist.github.com/DatrixTHLK/3772909e52de83d2fb7ba727e2cf6158

**Comment by Elix-x** [comment]
@DatrixTHLK thanks!
@mezz First 3 issue lines are from forestry, and it's because of incorect state?.. It seems that it's most likely issue on forestry's part...

**Comment by mezz** [comment]
Any blockstate will crash if you give it an invalid variant, I don't think this is from Forestry. Does Chisels and Bits have any Forestry-specific code?

**Comment by mezz** [comment]
I'll take a closer look when I get home, since Forestry is setting the variant.

**Comment by AlgorithmX2** [comment]
I don't have any mod specific code, that crash is pretty unusual, Are the creative tabs crashing? or just FEI?

**Comment by mezz** [comment]
I added some defensive code on Forestry's side, should prevent this from crashing.
In Forestry 5.2.14.265

**Comment by DatrixTHLK** [comment]
So far Just when I look into FEI @AlgorithmX2. Well if it is forestry then thanks for the precautionary method @mezz
